---
- name: Remove microservices stack from Kubernetes
  hosts: local
  gather_facts: false

  tasks:
    - name: Delete namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        state: absent
